### ISSUE TITLE
Global option isnt display when user type --help

### ISSUE THREAD

**Issue by SFzxc** [phradion/lgtm_hd#11]

**Comment by phradion** [comment]
Should work properly now in 0.2.0

![screen shot 2017-05-29 at 2 02 51 am](https://cloud.githubusercontent.com/assets/965536/26531419/f872ebb4-4412-11e7-80c4-7141dcb89fff.png)

**Comment by phradion** [comment]
@SFzxc can you confirm this?

**Comment by SFzxc** [comment]
Work as well!
