### ISSUE TITLE
to fix items from Code review by trung le

### ISSUE THREAD

**Issue by phradion** [phradion/lgtm_hd#9]
Thank you for your help! @joneslee85

> https://github.com/phradion/lgtm_hd/blob/master/lib/lgtm_hd.rb#L28

Remove `then`, why do we have to check if the instance respond to `combine_options`

-----

> https://github.com/phradion/lgtm_hd/blob/master/lib/lgtm_hd.rb#L12

* Use lowercase snake case, that means `URI` would be come `uri`
* You could use keyword argument to make your constructor meaningful, that is

```
 def initialize(input_image_uri:, output_image_uri:)

 end

 # when you construct them you run `MemeGenerator.new(input_image_uri: my_var, output_image_uri: another_var)`
```

----

> https://github.com/phradion/lgtm_hd/blob/master/lib/lgtm_hd.rb#L16

Should you `open` in the constructor? could you delay it until some method needs it? You could do this pattern, remove the `img` from the constructor then declare the `img` method:

```
private

def img
  @img ||= MiniMagick::Image.open(input_image_uri)
end
```

Everytime `img` method is invoke, it would hit the memoized `img`

----

> https://github.com/phradion/lgtm_hd/blob/master/lib/lgtm_hd.rb#L67

all method should be snake case

----

> https://github.com/phradion/lgtm_hd/blob/master/lib/lgtm_hd.rb#L115

no need to explicitly return, just remove the `return`, the last line is implicitly returned

----

> https://github.com/phradion/lgtm_hd/blob/master/lib/lgtm_hd.rb#L107-L113

The magic can be extracted to different methods

----

> https://github.com/phradion/lgtm_hd/blob/master/lib/lgtm_hd.rb#L98

Is there any reason why we could not work on the same img instance? Perf?

----

> https://github.com/phradion/lgtm_hd/blob/master/lib/lgtm_hd.rb#L59

remove `()`

----

> https://github.com/phradion/lgtm_hd/blob/master/lib/lgtm_hd.rb#L52

Why do you cast these two int to string?

if it is because you concat (https://github.com/phradion/lgtm_hd/blob/master/lib/lgtm_hd.rb#L36), you could always do string interpolation:

`c.resize imageMaxSize().reduce() { |w, h| "#{w}x${h}" }`

-----

> https://github.com/phradion/lgtm_hd/blob/master/lib/lgtm_hd.rb#L8

encapsulation: do we need to expose these two getter as public methods?

-----

> https://github.com/phradion/lgtm_hd/blob/master/lib/lgtm_hd.rb#L27

Remove space between method name and `()`

----

> https://github.com/phradion/lgtm_hd/blob/master/lib/lgtm_hd.rb#L7

can we extract this class to a separate file? the common pattern is that the main driver file is to load all rather than including logic

-----

> https://github.com/phradion/lgtm_hd/blob/master/lib/lgtm_hd/configuration.rb#L4

all constants in Ruby are not frozen, you need to cast `.freeze()`

---

> https://github.com/phradion/lgtm_hd/blob/master/lib/lgtm_hd/configuration.rb#L8-L11

line alignment

---

> https://github.com/phradion/lgtm_hd/blob/master/lib/lgtm_hd/cli.rb#L3-L5

I could not find anywhere in that file you use these libs

----

> https://github.com/phradion/lgtm_hd/blob/master/lib/lgtm_hd/cli.rb#L1

Is there any reason why you re-declare this include?

----

> https://github.com/phradion/lgtm_hd/blob/master/lib/lgtm_hd/cli.rb#L46

Please raise `ArgumentError` instead of `StandardError`

-----

> https://github.com/phradion/lgtm_hd/blob/master/lib/lgtm_hd/cli.rb#L61

I think the URI builder logic could be extracted to a private method, it is very confusing when I read it

-----

> https://github.com/phradion/lgtm_hd/blob/master/lib/lgtm_hd/cli.rb#L51

Why don't u reverse the negation with `!~` and `!File.exists?`. by the way, please use `||` instead of `or`, there are dinstinct differences between `or` and `||`, safest choice is to always go with `||`

**Comment by phradion** [comment]
Fixed.

**Comment by runlevel5** [comment]
👏

**Comment by runlevel5** [comment]
@phradion 

>https://github.com/phradion/lgtm_hd/blob/master/lib/lgtm_hd/configuration.rb#L15

Number and symbol are static, they aren't needed to be frozen. String if not frozen would instantiate  new object.

```
"irb(main):001:0> "232".object_id
=> 70267690872640
irb(main):002:0> "232".object_id
=> 70267690856060
```

whilst

```
irb(main):003:0> 123.object_id
=> 247
irb(main):004:0> 123.object_id
=> 247
```

**Comment by phradion** [comment]
🆗  @joneslee85  :bowing_woman:
